package com.crsk.openclaw.node

/**
 * The on-device `act` command. The agent only has openclaw's generic `exec` tool
 * (openclaw 2026.5.12 dropped stdio MCP, so native tap/observe tools can't be
 * registered — see NodeProcess.refreshMcpConfig). This wrapper collapses the
 * ~60-token curl-to-:3001 boilerplate the model used to emit on EVERY step into a
 * ~4-token call: `act tap 5`, `act type 5 hello`, `act observe`. It reads the bearer
 * token from the env openclaw already injects (OPENCLAW_GATEWAY_TOKEN), so the model
 * never spells out the Authorization header or the URL.
 *
 * Authored with `§` standing in for the shell `$` so we don't have to escape every
 * shell variable inside a Kotlin string; [render] swaps it back.
 */
object ActWrapperScript {

    private const val TEMPLATE = """#!/system/bin/sh
# act — thin wrapper over the on-device UI bridge on :3001.
# Generated by NodeProcess; DO NOT EDIT. The agent emits `act <verb> ...` via exec.
B='http://127.0.0.1:3001'
AUTH="Authorization: Bearer §OPENCLAW_GATEWAY_TOKEN"
CT='Content-Type: application/json'
verb="§1"
shift 2>/dev/null
esc() { printf '%s' "§1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
post() { exec curl -s -X POST -H "§CT" -H "§AUTH" -d "§1" "§2"; }
case "§verb" in
  observe|look|back|home) post "{\"verb\":\"§verb\"}" "§B/agent/act" ;;
  tap|double_tap)         post "{\"verb\":\"§verb\",\"id\":§1}" "§B/agent/act" ;;
  swipe)                  post "{\"verb\":\"swipe\",\"direction\":\"§1\"}" "§B/agent/act" ;;
  type)                   id="§1"; shift 2>/dev/null; post "{\"verb\":\"type\",\"id\":§id,\"text\":\"$(esc "§*")\"}" "§B/agent/act" ;;
  wait)                   txt="§1"; post "{\"verb\":\"wait\",\"text\":\"$(esc "§txt")\",\"timeout\":§{2:-3000}}" "§B/agent/act" ;;
  note)                   post "{\"verb\":\"note\",\"text\":\"$(esc "§*")\"}" "§B/agent/act" ;;
  take_over)              post "{\"verb\":\"take_over\",\"reason\":\"$(esc "§*")\"}" "§B/agent/act" ;;
  launch)                 post "{\"package\":\"§1\"}" "§B/ui/app/launch" ;;
  batch)                  post "{\"ops\":§1}" "§B/ui/batch" ;;
  *) echo "{\"ok\":false,\"error\":\"unknown act verb: §verb\"}"; exit 1 ;;
esac
"""

    fun render(): String = TEMPLATE.replace("§", "$")
}
