package com.crsk.openclaw.node

object LauncherScript {
    fun render(libDir: String, homeDir: String, shimEntry: String): String = """
        #!/system/bin/sh
        # Generated by NodeProcess.refreshMcpConfig — DO NOT EDIT
        # openclaw strips LD_* from MCP env (host-env-security blockedPrefixes).
        # Restore LD_LIBRARY_PATH here so libnode.so can find companion .so files.
        export LD_LIBRARY_PATH="$libDir"
        export HOME="$homeDir"
        exec "$libDir/libnode.so" "$shimEntry"
    """.trimIndent() + "\n"
}
